export type Category =
  | 'Ortodoncia'
  | 'Endodoncia'
  | 'Periodoncia'
  | 'Odontopediatría'
  | 'Implantes'
  | 'Estética Dental'
  | 'Blanqueamiento'
  | 'Cirugía'
  | 'Prótesis'
  | 'General'
  | 'Prevención y cuidado'
  | 'Rehabilitación y restauración dental'
  | 'Periodoncia (encías)'
  | 'Cirugía dental'
  | 'Urgencias dentales'
  | 'Estética dental';
